apiVersion: v1
kind: Service
metadata:
  name: repeatedservice  
spec:
  selector:
    app: repeatedservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 18606
      targetPort: 18606
      nodePort: 30002